
import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Classic White T-Shirt',
    sku: 'TS-WHT-M',
    price: 25.00,
    cost: 10.00,
    stock: 50,
    description: 'A comfortable and stylish 100% cotton white t-shirt.',
    imageUrl: 'https://picsum.photos/seed/tshirt/400/400',
    lowStockThreshold: 10,
  },
  {
    id: 'prod_2',
    name: 'Slim-Fit Denim Jeans',
    sku: 'JN-BLU-32',
    price: 75.00,
    cost: 30.00,
    stock: 30,
    description: 'Modern slim-fit jeans in a classic blue wash.',
    imageUrl: 'https://picsum.photos/seed/jeans/400/400',
    lowStockThreshold: 5,
  },
  {
    id: 'prod_3',
    name: 'Leather Biker Jacket',
    sku: 'JK-BLK-L',
    price: 250.00,
    cost: 120.00,
    stock: 8,
    description: 'A timeless biker jacket made from genuine leather.',
    imageUrl: 'https://picsum.photos/seed/jacket/400/400',
    lowStockThreshold: 5,
  },
  {
    id: 'prod_4',
    name: 'Beige Chino Shorts',
    sku: 'SH-BGE-34',
    price: 45.00,
    cost: 18.00,
    stock: 40,
    description: 'Versatile and comfortable chino shorts for any occasion.',
    imageUrl: 'https://picsum.photos/seed/shorts/400/400',
    lowStockThreshold: 10,
  },
  {
    id: 'prod_5',
    name: 'Wool Scarf',
    sku: 'AC-GRY-OS',
    price: 30.00,
    cost: 12.00,
    stock: 0,
    description: 'A warm and soft wool scarf in charcoal grey.',
    imageUrl: 'https://picsum.photos/seed/scarf/400/400',
    lowStockThreshold: 5,
  },
    {
    id: 'prod_6',
    name: 'Red Floral Sundress',
    sku: 'DR-RED-S',
    price: 85.00,
    cost: 35.00,
    stock: 12,
    description: 'A vibrant red sundress with a floral pattern.',
    imageUrl: 'https://picsum.photos/seed/sundress/400/400',
    lowStockThreshold: 5,
  },
];
